<a href="https://colab.research.google.com/github/wtryab-re/data-preprocessing/blob/main/Standardization_and_Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Standard Scaler for standardization, Min Max scaler for normalization?

In [29]:
!pip install -q scikit-learn numpy pandas

In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [31]:
df = load_iris(as_frame=True).frame
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [32]:
X = df.drop('target', axis=1)
y = df['target']

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [34]:
#fit onto train data only but transform BOTH test and train

In [35]:
num_cols = X.select_dtypes(include=np.number).columns.tolist()
cat_cols = list(filter(lambda x: x not in num_cols, X_train.columns))
num_cols, cat_cols

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 [])

#Standardization

Data standardization is a preprocessing technique that rescales numerical features to have a mean of 0 and a standard deviation of 1.

This prevents features with larger magnitudes from dominating the learning process and ensures algorithms converge faster and perform accurately.

Makes the mean approx 0, std approx 1

z = x - mean / std

In [36]:
X_train.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         120.000000        120.000000          120.00000        120.000000
mean            5.841667          3.048333            3.77000          1.205000
std             0.840926          0.448524            1.76852          0.762663
min             4.300000          2.000000            1.10000          0.100000
25%             5.100000          2.800000            1.60000          0.300000
50%             5.750000          3.000000            4.25000          1.300000
75%             6.400000          3.325000            5.10000          1.800000
max             7.900000          4.400000            6.90000          2.500000

In [42]:
scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test_scaled[num_cols] = scaler.transform(X_test[num_cols])

X_train_scaled.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count       1.200000e+02      1.200000e+02       1.200000e+02      1.200000e+02
mean       -1.369275e-16      9.992007e-16       1.665335e-17      1.702342e-16
std         1.004193e+00      1.004193e+00       1.004193e+00      1.004193e+00
min        -1.840983e+00     -2.347097e+00      -1.516067e+00     -1.454945e+00
25%        -8.856620e-01     -5.559895e-01      -1.232159e+00     -1.191606e+00
50%        -1.094638e-01     -1.082127e-01       2.725514e-01      1.250858e-01
75%         6.667343e-01      6.194245e-01       7.551944e-01      7.834318e-01
max         2.457961e+00      3.026225e+00       1.777262e+00      1.705116e+00

#Min Max Scaler - Normalization

In [43]:
max_scaler = MinMaxScaler()
X_train_maxed = X_train.copy()
X_test_maxed = X_test.copy()

X_train_maxed[num_cols] = max_scaler.fit_transform(X_train[num_cols])
X_test_maxed[num_cols] = max_scaler.transform(X_test[num_cols])

X_train_maxed.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         120.000000        120.000000         120.000000        120.000000
mean            0.428241          0.436806           0.460345          0.460417
std             0.233591          0.186885           0.304917          0.317776
min             0.000000          0.000000           0.000000          0.000000
25%             0.222222          0.333333           0.086207          0.083333
50%             0.402778          0.416667           0.543103          0.500000
75%             0.583333          0.552083           0.689655          0.708333
max             1.000000          1.000000           1.000000          1.000000

In [44]:
X_train_maxed.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8             0.027778          0.375000           0.051724          0.041667
106           0.166667          0.208333           0.586207          0.666667
76            0.694444          0.333333           0.637931          0.541667
9             0.166667          0.458333           0.068966          0.000000
89            0.333333          0.208333           0.500000          0.500000